nodeLinker: node-modules

enableGlobalCache: false

enableStrictSsl: false

packageExtensions:
  "@storybook/react@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/addon-docs@*":
    dependencies:
      react: "*"
      react-dom: "*"

npmScopes:
  shimo:
    npmRegistryServer: 'http://registry.npm.shimo.run'

yarnPath: .yarn/releases/yarn-4.9.1.cjs
