import { colors } from '../base';
import type { ButtonConfig } from '@officesdk/editor-sdk-core/shared';

export const button: ButtonConfig = {
  icons: {
    close: {
      url: '',
      size: { width: '16px', height: '16px' },
    },
    clear: {
      url: '',
      size: { width: '16px', height: '16px' },
    },
    search: {
      url: '',
      size: { width: '16px', height: '16px' },
    },
  },
  solid: {
    default: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['120']} 0%, ${colors.palettes.gray['90']} 100%)`,
      backgroundHover: colors.palettes.transparency['80'],
      backgroundActive: colors.palettes.gray['120'],
      backgroundDisabled: colors.palettes.transparency['30'],
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    guidance: {
      background: `linear-gradient(0deg, ${colors.palettes.blue['7']} 0%, ${colors.palettes.blue['5']} 100%)`,
      backgroundHover: colors.palettes.blue['6'],
      backgroundActive: colors.palettes.blue['7'],
      backgroundDisabled: 'rgba(91, 160, 231, 0.30)',
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    alert: {
      background: `linear-gradient(0deg, ${colors.palettes.red['8']} 0%, ${colors.palettes.red['6']} 100%)`,
      backgroundHover: colors.palettes.red['6'],
      backgroundActive: colors.palettes.red['7'],
      backgroundDisabled: 'rgba(233, 85, 85, 0.30)',
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
  },
  outlined: {
    default: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.brand,
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    guidance: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    alert: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.red['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
  },
  text: {
    default: {
      background: 'transparent',
      backgroundHover: colors.palettes.transparency['5'],
      backgroundActive: colors.palettes.transparency['10'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.brand,
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    guidance: {
      background: 'transparent',
      backgroundHover: colors.palettes.blue['1'],
      backgroundActive: colors.palettes.blue['2'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    alert: {
      background: 'transparent',
      backgroundHover: colors.palettes.red['1'],
      backgroundActive: colors.palettes.red['2'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.red['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    status: {
      background: colors.palettes.blue['1'],
      backgroundHover: colors.palettes.blue['2'],
      backgroundActive: colors.palettes.blue['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
  },
  small: {
    height: '28px',
    padding: '4px 12px',
    fontSize: '13px',
    lineHeight: '20px',
    borderRadius: '4px',
    iconSize: { width: '14px', height: '14px' },
    iconGap: '4px',
  },
  medium: {
    height: '32px',
    padding: '6px 16px',
    fontSize: '14px',
    lineHeight: '20px',
    borderRadius: '4px',
    iconSize: { width: '16px', height: '16px' },
    iconGap: '6px',
  },
  large: {
    height: '36px',
    padding: '8px 20px',
    fontSize: '14px',
    lineHeight: '20px',
    borderRadius: '4px',
    iconSize: { width: '16px', height: '16px' },
    iconGap: '6px',
  },
  extraLarge: {
    height: '40px',
    padding: '10px 24px',
    fontSize: '14px',
    lineHeight: '20px',
    borderRadius: '4px',
    iconSize: { width: '16px', height: '16px' },
    iconGap: '8px',
  },
};
