import { borderRadius, colors } from '../base';
import type { ButtonConfig } from '@officesdk/editor-sdk-core/shared';

export const button: ButtonConfig = {
  solid: {
    default: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['120']} 0%, ${colors.palettes.gray['90']} 100%)`,
      backgroundHover: colors.palettes.transparency['80'],
      backgroundActive: colors.palettes.gray['120'],
      backgroundDisabled: colors.palettes.transparency['30'],
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    guidance: {
      background: `linear-gradient(0deg, ${colors.palettes.blue['7']} 0%, ${colors.palettes.blue['5']} 100%)`,
      backgroundHover: colors.palettes.blue['6'],
      backgroundActive: colors.palettes.blue['7'],
      backgroundDisabled: 'rgba(91, 160, 231, 0.30)',
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
    alert: {
      background: `linear-gradient(0deg, ${colors.palettes.red['8']} 0%, ${colors.palettes.red['6']} 100%)`,
      backgroundHover: colors.palettes.red['6'],
      backgroundActive: colors.palettes.red['7'],
      backgroundDisabled: 'rgba(233, 85, 85, 0.30)',
      color: colors.palettes.gray['0'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.gray['0'],
      colorActive: colors.palettes.gray['0'],
      colorDisabled: colors.palettes.gray['0'],
    },
  },
  outlined: {
    default: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.brand,
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.brand,
      colorActive: colors.palettes.brand,
      colorDisabled: colors.palettes.transparency['30'],
    },
    guidance: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.blue['6'],
      colorActive: colors.palettes.blue['6'],
      colorDisabled: colors.palettes.transparency['30'],
    },
    alert: {
      background: `linear-gradient(0deg, ${colors.palettes.gray['5']} 0%, ${colors.palettes.gray['0']} 100%)`,
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.red['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      fontWeight: 500,
      colorHover: colors.palettes.red['6'],
      colorActive: colors.palettes.red['6'],
      colorDisabled: colors.palettes.transparency['30'],
    },
  },
  text: {
    default: {
      background: 'transparent',
      backgroundHover: colors.palettes.transparency['5'],
      backgroundActive: colors.palettes.transparency['10'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.brand,
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 400,
      colorHover: colors.palettes.brand,
      colorActive: colors.palettes.brand,
      colorDisabled: colors.palettes.transparency['30'],
    },
    guidance: {
      background: 'transparent',
      backgroundHover: colors.palettes.transparency['5'],
      backgroundActive: colors.palettes.transparency['10'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 400,
      colorHover: colors.palettes.blue['6'],
      colorActive: colors.palettes.blue['6'],
      colorDisabled: colors.palettes.transparency['30'],
    },
    alert: {
      background: 'transparent',
      backgroundHover: colors.palettes.transparency['5'],
      backgroundActive: colors.palettes.transparency['10'],
      backgroundDisabled: 'transparent',
      color: colors.palettes.red['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 400,
      colorHover: colors.palettes.red['6'],
      colorActive: colors.palettes.red['6'],
      colorDisabled: colors.palettes.transparency['30'],
    },
    status: {
      background: colors.palettes.blue['1'],
      backgroundHover: colors.palettes.blue['2'],
      backgroundActive: colors.palettes.blue['3'],
      backgroundDisabled: colors.palettes.transparency['5'],
      color: colors.palettes.blue['6'],
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
      borderColor: 'transparent',
      borderColorHover: 'transparent',
      borderColorActive: 'transparent',
      borderColorDisabled: 'transparent',
      fontWeight: 400,
      colorHover: colors.palettes.blue['6'],
      colorActive: colors.palettes.blue['6'],
      colorDisabled: colors.palettes.transparency['60'],
    },
  },
  small: {
    withIcon: {
      height: '24px',
      padding: '0px 10px',
      textPadding: '0 2px',
      fontSize: '12px',
      lineHeight: '20px',
      borderRadius: borderRadius.small,
      iconSize: { width: '16px', height: '16px' },
      iconGap: '4px',
    },
    onlyIcon: {
      iconSize: { width: '12px', height: '12px' },
      padding: '6px',
      borderRadius: borderRadius.small,
    },
  },
  medium: {
    withIcon: {
      height: '28px',
      padding: '2px 14px',
      textPadding: '0 2px',
      fontSize: '13px',
      lineHeight: '20px',
      borderRadius: borderRadius.small,
      iconSize: { width: '16px', height: '16px' },
      iconGap: '4px',
    },
    onlyIcon: {
      iconSize: { width: '14px', height: '14px' },
      padding: '7px',
      borderRadius: borderRadius.small,
    },
  },
  large: {
    withIcon: {
      height: '32px',
      padding: '0 18px',
      textPadding: '0 6px',
      fontSize: '13px',
      lineHeight: '20px',
      borderRadius: borderRadius.small,
      iconSize: { width: '18px', height: '18px' },
      iconGap: '4px',
    },
    onlyIcon: {
      iconSize: { width: '16px', height: '16px' },
      padding: '8px',
      borderRadius: borderRadius.small,
    },
  },
  extraLarge: {
    withIcon: {
      height: '40px',
      padding: '0px 26px',
      textPadding: '0px 6px',
      fontSize: '16px',
      lineHeight: '24px',
      borderRadius: borderRadius.small,
      iconSize: { width: '16px', height: '16px' },
      iconGap: '4px',
    },
    onlyIcon: {
      iconSize: { width: '20px', height: '20px' },
      padding: '10px',
      borderRadius: borderRadius.small,
    },
  },
};
