import { colors } from '../base';
import { InputConfig } from '@officesdk/editor-sdk-core/shared';

export const input: InputConfig = {
  outlined: {
    state: {
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      borderColorError: colors.palettes.red['6'],
      borderColorReadonly: colors.palettes.transparency['10'],
      background: colors.palettes.gray['0'],
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['0'],
      backgroundDisabled: colors.palettes.gray['5'],
      backgroundReadonly: colors.palettes.gray['2'],
      placeholderColorNormal: colors.palettes.transparency['30'],
      placeholderColorHover: colors.palettes.transparency['30'],
      textColorNormal: colors.palettes.gray['120'],
      textColorDisabled: colors.palettes.transparency['30'],
      textColorReadOnly: colors.palettes.transparency['30'],
    },
    mini: {
      height: '20px',
      borderRadius: '4px',
      padding: '0px 4px',
      contentPadding: '0px 0',
      gap: '4px',
      iconSize: { width: '12px', height: '12px' },
      clearIcon: {
        size: { width: '12px', height: '12px' },
      },
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    small: {
      height: '24px',
      borderRadius: '4px',
      padding: '0px 4px',
      contentPadding: '2px 4px',
      gap: '4px',
      iconSize: { width: '14px', height: '14px' },
      clearIcon: {
        size: { width: '14px', height: '14px' },
      },
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    medium: {
      height: '32px',
      borderRadius: '4px',
      padding: '2px 8px',
      contentPadding: '4px',
      gap: '4px',
      iconSize: { width: '18px', height: '18px' },
      clearIcon: {
        size: { width: '18px', height: '18px' },
      },
      fontSize: '13px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    large: {
      height: '40px',
      borderRadius: '4px',
      padding: '4px 4px 4px 12px',
      contentPadding: '4px 8px',
      gap: '4px',
      iconSize: { width: '20px', height: '20px' },
      clearIcon: {
        size: { width: '20px', height: '20px' },
      },
      fontSize: '14px',
      lineHeight: '24px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
  },
  underlined: {
    state: {
      borderColor: 'transparent',
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: 'transparent',
      borderColorError: colors.palettes.red['6'],
      borderColorReadonly: 'transparent',
      background: 'transparent',
      backgroundHover: 'transparent',
      backgroundActive: 'transparent',
      backgroundDisabled: 'transparent',
      backgroundReadonly: 'transparent',
      placeholderColorNormal: colors.palettes.transparency['30'],
      placeholderColorHover: colors.palettes.transparency['30'],
      textColorNormal: colors.palettes.gray['120'],
      textColorDisabled: colors.palettes.transparency['30'],
      textColorReadOnly: colors.palettes.transparency['30'],
    },
    mini: {
      height: '24px',
      padding: '0 4px',
      contentPadding: '4px 0 4px 4px',
      gap: '4px',
      fontSize: '12px',
      lineHeight: '20px',
      iconSize: { width: '16px', height: '16px' },
      clearIcon: {
        size: { width: '16px', height: '16px' },
      },
      borderRadius: '4px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    small: {
      height: '24px',
      padding: '0 4px',
      contentPadding: '4px 0 4px 4px',
      gap: '4px',
      fontSize: '12px',
      lineHeight: '20px',
      iconSize: { width: '16px', height: '16px' },
      clearIcon: {
        size: { width: '16px', height: '16px' },
      },
      borderRadius: '4px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none'
    },
    medium: {
      height: '32px',
      padding: '0 8px',
      contentPadding: '6px 0 6px 4px',
      gap: '4px',
      fontSize: '13px',
      lineHeight: '20px',
      iconSize: { width: '18px', height: '18px' },
      clearIcon: {
        size: { width: '16px', height: '16px' },
      },
      borderRadius: '4px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    large: {
      height: '40px',
      padding: '10px 12px',
      contentPadding: '0 0 0 4px',
      gap: '4px',
      fontSize: '14px',
      lineHeight: '24px',
      iconSize: { width: '20px', height: '20px' },
      clearIcon: {
        size: { width: '16px', height: '16px' },
      },
      borderRadius: '4px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
  },
};
