import { colors } from '../base';
import { InputConfig } from '@officesdk/editor-sdk-core/shared';

export const input: InputConfig = {
  icons: {
    search: {
      url: '',
      size: { width: '16px', height: '16px' },
    },
    clear: {
      url: '',
      size: { width: '16px', height: '16px' },
    },
  },
  outlined: {
    state: {
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      borderColorError: colors.palettes.red['6'],
      borderColorReadonly: colors.palettes.transparency['10'],
      background: colors.palettes.gray['0'],
      backgroundHover: colors.palettes.gray['0'],
      backgroundActive: colors.palettes.gray['0'],
      backgroundDisabled: colors.palettes.gray['5'],
      backgroundReadonly: colors.palettes.gray['2'],
    },
    mini: {
      borderRadius: '4px',
      iconSize: { width: '12px', height: '12px' },
      padding: '2px 4px',
      height: '20px',
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    small: {
      borderRadius: '4px',
      iconSize: { width: '14px', height: '14px' },
      padding: '2px 4px',
      height: '24px',
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    medium: {
      borderRadius: '4px',
      iconSize: { width: '18px', height: '18px' },
      padding: '4px 8px',
      height: '32px',
      fontSize: '13px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    large: {
      borderRadius: '4px',
      iconSize: { width: '18px', height: '18px' },
      padding: '4px 8px',
      height: '32px',
      fontSize: '13px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
    extraLarge: {
      borderRadius: '4px',
      iconSize: { width: '20px', height: '20px' },
      padding: '6px 12px',
      height: '40px',
      fontSize: '14px',
      lineHeight: '24px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: '0 2px 8px 0 rgba(0, 0, 0, 0.04)',
      boxShadowDisabled: 'none',
    },
  },
  underlined: {
    state: {
      borderColor: colors.palettes.transparency['10'],
      borderColorHover: colors.palettes.transparency['20'],
      borderColorActive: colors.palettes.transparency['30'],
      borderColorDisabled: colors.palettes.transparency['10'],
      borderColorError: colors.palettes.red['6'],
      borderColorReadonly: colors.palettes.transparency['10'],
      background: 'transparent',
      backgroundHover: 'transparent',
      backgroundActive: 'transparent',
      backgroundDisabled: 'transparent',
      backgroundReadonly: 'transparent',
    },
    mini: {
      borderRadius: '0',
      iconSize: { width: '12px', height: '12px' },
      padding: '2px 0',
      height: '20px',
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    small: {
      borderRadius: '0',
      iconSize: { width: '14px', height: '14px' },
      padding: '2px 0',
      height: '24px',
      fontSize: '12px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    medium: {
      borderRadius: '0',
      iconSize: { width: '18px', height: '18px' },
      padding: '4px 0',
      height: '32px',
      fontSize: '13px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    large: {
      borderRadius: '0',
      iconSize: { width: '18px', height: '18px' },
      padding: '4px 0',
      height: '32px',
      fontSize: '13px',
      lineHeight: '20px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
    extraLarge: {
      borderRadius: '0',
      iconSize: { width: '20px', height: '20px' },
      padding: '6px 0',
      height: '40px',
      fontSize: '14px',
      lineHeight: '24px',
      boxShadow: 'none',
      boxShadowHover: 'none',
      boxShadowActive: 'none',
      boxShadowDisabled: 'none',
    },
  },
};

