/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generate-registry.ts
 *
 * This file exports all icon components directly from SVG files.
 */
import { ReactComponent as AlignCenterIcon } from './svg/text/align-center.svg';
import { ReactComponent as AlignJustifyIcon } from './svg/text/align-justify.svg';
import { ReactComponent as AlignLeftIcon } from './svg/text/align-left.svg';
import { ReactComponent as AlignRightIcon } from './svg/text/align-right.svg';
import { ReactComponent as ArrowDownIcon } from './svg/arrows/arrow-down.svg';
import { ReactComponent as ArrowLeftIcon } from './svg/arrows/arrow-left.svg';
import { ReactComponent as ArrowRightIcon } from './svg/arrows/arrow-right.svg';
import { ReactComponent as ArrowUpIcon } from './svg/arrows/arrow-up.svg';
import { ReactComponent as BackIcon } from './svg/main-site/back.svg';
import { ReactComponent as BoldIcon } from './svg/text/bold.svg';
import { ReactComponent as CheckIcon } from './svg/general/check.svg';
import { ReactComponent as ChevronDownIcon } from './svg/arrows/chevron-down.svg';
import { ReactComponent as ChevronUpIcon } from './svg/arrows/chevron-up.svg';
import { ReactComponent as ClearFormatIcon } from './svg/general/clear-format.svg';
import { ReactComponent as CloseIcon } from './svg/general/close.svg';
import { ReactComponent as CopyIcon } from './svg/general/copy.svg';
import { ReactComponent as CutIcon } from './svg/general/cut.svg';
import { ReactComponent as DeleteIcon } from './svg/general/delete.svg';
import { ReactComponent as DownloadIcon } from './svg/main-site/download.svg';
import { ReactComponent as EditIcon } from './svg/main-site/edit.svg';
import { ReactComponent as ErrorIcon } from './svg/status/error.svg';
import { ReactComponent as ExitFullscreenIcon } from './svg/utility/exit-fullscreen.svg';
import { ReactComponent as FilterIcon } from './svg/main-site/filter.svg';
import { ReactComponent as FlipHorizontalIcon } from './svg/image/flip-horizontal.svg';
import { ReactComponent as FlipVerticalIcon } from './svg/image/flip-vertical.svg';
import { ReactComponent as FormatBrushIcon } from './svg/general/format-brush.svg';
import { ReactComponent as FreezeIcon } from './svg/table/freeze.svg';
import { ReactComponent as FullscreenIcon } from './svg/utility/fullscreen.svg';
import { ReactComponent as GridIcon } from './svg/main-site/grid.svg';
import { ReactComponent as HideIcon } from './svg/general/hide.svg';
import { ReactComponent as ImageIcon } from './svg/image/image.svg';
import { ReactComponent as IndentDecreaseIcon } from './svg/text/indent-decrease.svg';
import { ReactComponent as IndentIncreaseIcon } from './svg/text/indent-increase.svg';
import { ReactComponent as InfoIcon } from './svg/status/info.svg';
import { ReactComponent as ItalicIcon } from './svg/text/italic.svg';
import { ReactComponent as LinkIcon } from './svg/text/link.svg';
import { ReactComponent as ListIcon } from './svg/main-site/list.svg';
import { ReactComponent as ListBulletIcon } from './svg/text/list-bullet.svg';
import { ReactComponent as ListNumberIcon } from './svg/text/list-number.svg';
import { ReactComponent as LoadingIcon } from './svg/status/loading.svg';
import { ReactComponent as MenuIcon } from './svg/main-site/menu.svg';
import { ReactComponent as MergeCellsIcon } from './svg/table/merge-cells.svg';
import { ReactComponent as MinusIcon } from './svg/general/minus.svg';
import { ReactComponent as MoreIcon } from './svg/utility/more.svg';
import { ReactComponent as PasteIcon } from './svg/general/paste.svg';
import { ReactComponent as PlusIcon } from './svg/general/plus.svg';
import { ReactComponent as PrintIcon } from './svg/general/print.svg';
import { ReactComponent as QuestionIcon } from './svg/status/question.svg';
import { ReactComponent as RedoIcon } from './svg/general/redo.svg';
import { ReactComponent as RefreshIcon } from './svg/utility/refresh.svg';
import { ReactComponent as RotateLeftIcon } from './svg/image/rotate-left.svg';
import { ReactComponent as RotateRightIcon } from './svg/image/rotate-right.svg';
import { ReactComponent as SaveIcon } from './svg/general/save.svg';
import { ReactComponent as SearchIcon } from './svg/general/search.svg';
import { ReactComponent as SelectAllIcon } from './svg/general/select-all.svg';
import { ReactComponent as SettingsIcon } from './svg/main-site/settings.svg';
import { ReactComponent as ShareIcon } from './svg/main-site/share.svg';
import { ReactComponent as SortIcon } from './svg/main-site/sort.svg';
import { ReactComponent as SplitCellsIcon } from './svg/table/split-cells.svg';
import { ReactComponent as StrikethroughIcon } from './svg/text/strikethrough.svg';
import { ReactComponent as SuccessIcon } from './svg/status/success.svg';
import { ReactComponent as TableIcon } from './svg/table/table.svg';
import { ReactComponent as UnderlineIcon } from './svg/text/underline.svg';
import { ReactComponent as UndoIcon } from './svg/general/undo.svg';
import { ReactComponent as UploadIcon } from './svg/main-site/upload.svg';
import { ReactComponent as WarningIcon } from './svg/status/warning.svg';
import { ReactComponent as WorkbenchIcon } from './svg/general/workbench.svg';

export {
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BackIcon,
  BoldIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ClearFormatIcon,
  CloseIcon,
  CopyIcon,
  CutIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  ErrorIcon,
  ExitFullscreenIcon,
  FilterIcon,
  FlipHorizontalIcon,
  FlipVerticalIcon,
  FormatBrushIcon,
  FreezeIcon,
  FullscreenIcon,
  GridIcon,
  HideIcon,
  ImageIcon,
  IndentDecreaseIcon,
  IndentIncreaseIcon,
  InfoIcon,
  ItalicIcon,
  LinkIcon,
  ListIcon,
  ListBulletIcon,
  ListNumberIcon,
  LoadingIcon,
  MenuIcon,
  MergeCellsIcon,
  MinusIcon,
  MoreIcon,
  PasteIcon,
  PlusIcon,
  PrintIcon,
  QuestionIcon,
  RedoIcon,
  RefreshIcon,
  RotateLeftIcon,
  RotateRightIcon,
  SaveIcon,
  SearchIcon,
  SelectAllIcon,
  SettingsIcon,
  ShareIcon,
  SortIcon,
  SplitCellsIcon,
  StrikethroughIcon,
  SuccessIcon,
  TableIcon,
  UnderlineIcon,
  UndoIcon,
  UploadIcon,
  WarningIcon,
  WorkbenchIcon,
};
