/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generate-registry.ts
 */

export type ArrowsIconName =
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'chevron-down'
  | 'chevron-up';

export type GeneralIconName =
  | 'check'
  | 'clear-format'
  | 'close'
  | 'copy'
  | 'cut'
  | 'delete'
  | 'format-brush'
  | 'hide'
  | 'minus'
  | 'paste'
  | 'plus'
  | 'print'
  | 'redo'
  | 'save'
  | 'search'
  | 'select-all'
  | 'undo'
  | 'workbench';

export type ImageIconName =
  | 'flip-horizontal'
  | 'flip-vertical'
  | 'image'
  | 'rotate-left'
  | 'rotate-right';

export type MainSiteIconName =
  | 'back'
  | 'download'
  | 'edit'
  | 'filter'
  | 'grid'
  | 'list'
  | 'menu'
  | 'settings'
  | 'share'
  | 'sort'
  | 'upload';

export type StatusIconName =
  | 'error'
  | 'info'
  | 'loading'
  | 'question'
  | 'success'
  | 'warning';

export type TableIconName =
  | 'freeze'
  | 'merge-cells'
  | 'split-cells'
  | 'table';

export type TextIconName =
  | 'align-center'
  | 'align-justify'
  | 'align-left'
  | 'align-right'
  | 'bold'
  | 'indent-decrease'
  | 'indent-increase'
  | 'italic'
  | 'link'
  | 'list-bullet'
  | 'list-number'
  | 'strikethrough'
  | 'underline';

export type UtilityIconName =
  | 'exit-fullscreen'
  | 'fullscreen'
  | 'more'
  | 'refresh';

/**
 * All icon names union type
 */
export type IconName =
  | ArrowsIconName
  | GeneralIconName
  | ImageIconName
  | MainSiteIconName
  | StatusIconName
  | TableIconName
  | TextIconName
  | UtilityIconName;
